resources:
  repositories:
    - repository: templates
      type: github
      name: NSLS-II/profile-collection-ci
      ref: refs/heads/main
      endpoint: github

jobs:
  - template: nsls2-collection-2021-2.0.yml@templates
    parameters:
      beamline_acronym: CSX
  - template: nsls2-collection-2021-2.0-py39.yml@templates
    parameters:
      beamline_acronym: CSX
  - template: nsls2-collection-2021-3.0-py37.yml@templates
    parameters:
      beamline_acronym: CSX
  - template: nsls2-collection-2021-3.0-py39.yml@templates
    parameters:
      beamline_acronym: CSX
