resources:
  repositories:
    - repository: templates
      type: github
      name: NSLS-II/profile-collection-ci
      ref: refs/heads/main
      endpoint: github

jobs:
  - template: 2022-2.2-py39-tiled.yml@templates
    parameters:
      beamline_acronym: CSX
  - template: 2022-3.1-py39-tiled.yml@templates
    parameters:
      beamline_acronym: CSX
  - template: 2023-1.2-py39-tiled.yml@templates
    parameters:
      beamline_acronym: CSX
  - template: 2023-1.2-py310-tiled.yml@templates
    parameters:
      beamline_acronym: CSX
