resources:
  repositories:
    - repository: templates
      type: github
      name: NSLS-II/profile-collection-ci
      ref: refs/heads/2021-3.1
      endpoint: github

jobs:
  - template: nsls2-collection-2021-2.2-py37.yml@templates
    parameters:
      beamline_acronym: CSX
  - template: nsls2-collection-2021-2.2-py39.yml@templates
    parameters:
      beamline_acronym: CSX
  - template: nsls2-collection-2021-3.1-py37.yml@templates
    parameters:
      beamline_acronym: CSX
  - template: nsls2-collection-2021-3.1-py39.yml@templates
    parameters:
      beamline_acronym: CSX
  - template: nsls2-collection-2021-3.1-py37.yml@templates
    parameters:
      beamline_acronym: CSX
  - template: nsls2-collection-2021-3.1-py39.yml@templates
    parameters:
      beamline_acronym: CSX
